---
title: "Week 13 Class A"
author: "Cynthia Petrossian"
date: "4/26/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load Libraries
```{r}
library(tidyverse)
library(here)
```

# Simple for loop
```{r}
print(paste("The year is", 2000))
years<-c(2015:2021)
for (i in years){ # set up the for loop where i is the index
  print(paste("The year is", i)) # loop over i
}

#Pre-allocate space for the loop
#empty matrix
year_data <- data.frame(matrix(ncol = 2, nrow = length(years)))

#add column names
colnames(year_data) <- c("year", "year_name")
year_data

for(i in 1:length(years)){
  year_data$year_name[i] <- paste("The year is", years[i])
  year_data$year[i] <- years[i]
}
year_data
```

# Loops to read in multiple .csv files
```{r}
testdata<-read_csv(here("Week_13", "data", "cond_data","011521_CT316_1pcal.csv"))

glimpse(testdata)

# point to the location on the computer of the folder
CondPath<-here("Week_13", "Data", "cond_data")
# list all the files in that path with a specific pattern
# In this case we are looking for everything that has a .csv in the filename
# you can use regex to be more specific if you are looking for certain patterns in filenames
files <- dir(path = CondPath,pattern = ".csv")
files

# pre-allocate space
# make an empty dataframe that has one row for each file and 3 columns
cond_data<-data.frame(matrix(nrow = length(files), ncol = 3))
# give the dataframe column names
colnames(cond_data)<-c("filename","mean_temp", "mean_sal")
cond_data

raw_data<-read_csv(paste0(CondPath,"/",files[1])) # test by reading in the first file and see if it works
head(raw_data)

for (i in 1:length(files)){ # loop over 1:3 the number of files 
raw_data<-read_csv(paste0(CondPath,"/",files[i]))
#glimpse(raw_data)
cond_data$filename[i]<-files[i]
cond_data$mean_temp[i]<-mean(raw_data$Temperature, na.rm =TRUE)
cond_data$mean_sal[i]<-mean(raw_data$Salinity, na.rm =TRUE)
}

```

# map functions
```{r}
1:10 # a vector from 1 to 10 (we are going to do this 10 times)
1:10 %>% 
  map(rnorm, n = 15) %>% 
  map_dbl(mean)

1:10 %>% 
  map(function(x) rnorm(15, x)) %>% 
  map_dbl(mean)

1:10 %>% 
  map(~ rnorm(15, .x)) %>% 
  map_dbl(mean)

files <- dir(path = CondPath,pattern = ".csv", full.names = TRUE)
#save the entire path name
files

data<-files %>%
  set_names()%>% # set's the id of each list to the file name
  map_df(read_csv,.id = "filename") %>%  # map everything to a dataframe and put the id in a column called filename
group_by(filename) %>%
  summarise(mean_temp = mean(Temperature, na.rm = TRUE),
            mean_sal = mean(Salinity,na.rm = TRUE))
data
```

