---
title: "Week 12 Class B"
author: "Cynthia Petrossian"
date: "4/21/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load Libraries
```{r}
library(tidyverse)
library(here)
```

# Read In Data
```{r}
income_mean <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-02-09/income_mean.csv')
```

# Creating A Factor
```{r}
fruits <- factor(c("Apple", "Grape", "Banana"))
fruits

test <- c("A", "1", "2")
as.numeric(test)
test <- factor(test)
as.numeric(test)
```

# {forcats}
```{r}
glimpse(starwars)

starwars %>% 
  filter(!is.na(species)) %>% 
  count(species, sort = TRUE)

star_counts <- starwars %>% 
  filter(!is.na(species)) %>% 
  mutate(species = fct_lump(species, n=3)) %>% 
  count(species)

star_counts %>% 
  ggplot(aes(x = species,
             y = n))+
  geom_col()

star_counts %>% 
  ggplot(aes(x = fct_reorder(species, n),
             y = n))+
  geom_col()

star_counts %>% 
  ggplot(aes(x = fct_reorder(species, n, .desc = TRUE),
             y = n))+
  geom_col()+
  labs(x = "Species")
```

# Reordering line plots
```{r}
glimpse(income_mean)

total_income <- income_mean %>% 
  group_by(year, income_quintile) %>% 
  summarise(income_dollars_sum = sum(income_dollars)) %>% 
  mutate(income_quintile = factor(income_quintile))

total_income %>% 
  ggplot(aes(x = year,
             y = income_dollars_sum,
             color = fct_reorder2(income_quintile,year,income_dollars_sum)))+
  geom_line()+
  labs(color = "income quantile")
```

# Reorder Levels Directly In A Vector
```{r}
x1 <- factor(c("Jan", "Mar", "Apr", "Dec"))
x1

x1 <- factor(c("Jan", "Mar", "Apr", "Dec"), levels = c("Jan", "Mar", "Apr", "Dec"))
x1
```

#Subset Data with Factors
```{r}
starwars_clean <- starwars %>% 
  filter(!is.na(species)) %>% 
  count(species, sort = TRUE) %>% 
  mutate(species = factor(species)) %>% 
  filter(n>3) %>% 
  droplevels() %>% 
  mutate(species = fct_recode(species, "Humanoid" = "Human"))
starwars_clean
```

